DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username VARCHAR NOT NULL,
	first_name VARCHAR NOT NULL,
	last_name VARCHAR NOT NULL,
	password VARCHAR(255) NOT NULL,
	email VARCHAR NOT NULL,
	age INTEGER,
	gender VARCHAR,
	profilePic VARCHAR
);

DROP TABLE IF EXISTS restaurants;
CREATE TABLE restaurants (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR NOT NULL,
	description VARCHAR NOT NULL,
	price FLOAT,
	category VARCHAR NOT NULL,
	website VARCHAR,
	inauguration DATE,
  location_id FLOAT NOT NULL
);

DROP TABLE IF EXISTS restaurant_user;
CREATE TABLE restaurant_user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	restaurant_id INTEGER REFERENCES restaurants NOT NULL,
	user_id INTEGER REFERENCES users NOT NULL
);

DROP TABLE IF EXISTS reviews;
CREATE TABLE reviews (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER REFERENCES users NOT NULL,
	restaurant_id INTEGER REFERENCES restaurants NOT NULL,
	title VARCHAR NOT NULL,
	score INTEGER NOT NULL,
	body VARCHAR NOT NULL,
	date TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS replies;
CREATE TABLE replies (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
  review_id INTEGER REFERENCES reviews NOT NULL,
  user_id INTEGER REFERENCES users NOT NULL,
	date TIMESTAMP NOT NULL,
	body VARCHAR NOT NULL
);

DROP TABLE IF EXISTS images;
CREATE TABLE images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
	restaurant_id INTEGER REFERENCES restaurants NOT NULL,
  title VARCHAR NOT NULL,
	extension VARCHAR NOT NULL
);